### ISSUE TITLE
【请求移除】china_domain移除mikanani.me

### ISSUE THREAD

**Issue by seuqo** [txthinking/bypass#13]
根据 [【关于 Mikanani.me 被墙的临时解决方法。】](https://github.com/EstrellaXD/Auto_Bangumi/issues/196)，以及站长之家多地Ping[测试](https://ping.chinaz.com/mikannani.me)，mikanani.me 蜜柑计划现被封锁，希望从china_domain.txt中移除

**Comment by txthinking** [comment]
已merge。小提示：在commit message 里填写：fix #13 就会PR被merge后就会自动关闭对应的issue
