### ISSUE TITLE
一个疑惑

### ISSUE THREAD

**Issue by Bryan2333** [txthinking/bypass#6]
请问一下，Global和nonchina这两个的区别是什么？

**Comment by txthinking** [comment]
文件名没有下划线的 或 .list结尾的是为了保持兼容可能有人在用，后续会移除

**Comment by Bryan2333** [comment]
还有，google的IP段里应该是包含了youtube的IP段的吧？

**Comment by txthinking** [comment]
理论上是. 但实际可能不精确/不全.

**Comment by Bryan2333** [comment]
Ok
